### ISSUE TITLE
R hotkey for recording does not work

### ISSUE THREAD

**Issue by kingjasko** [xenonsb/Haxball-Room-Extension#22] opened 2019-10-25 15:17 UTC
The R hotkey for recording does not work. (yes I have the option ticked)

edit : another annoying thing is when you press "¸" to hide and show chat, if you hide it and then press tab, it will add space before whatever you type, so if a host has any commands you'd have to delete the space first in order for those commands to work.

**Comment by xenonsb** [comment] 2019-10-28 01:43
Regarding the R hotkey - right now it's only supposed to work in the "game-view". When you're in the room lobby view (where you can see names of players/specs), the hotkey isn't working as intended. I'm planning to fix that after.

Related issue: https://github.com/xenonsb/Haxball-Room-Extension/issues/11#issuecomment-545557049

**Comment by xenonsb** [comment] 2019-10-28 01:44
> edit : another annoying thing is when you press "¸" to hide and show chat, if you hide it and then press tab, it will add space before whatever you type, so if a host has any commands you'd have to delete the space first in order for those commands to work.

Interesting - what browser are you using? I have the same configuration and it hasn't added spaces in the chat..

**Comment by kingjasko** [comment] 2019-10-29 16:52
I'm using Chromium with --disable-frame-rate-limit parameter used in the shortcut properties.

**Comment by xenonsb** [comment] 2019-11-04 00:00
Hey @kingjasko, sorry I haven't been able to replicate this issue myself.. But as for the recording R hotkey, the fix is incorporated as of 0.3.4.

**Comment by Wazarr94** [comment] 2019-11-10 15:23
works for me now

**Closed as completed** 2020-09-09 01:38 UTC
Labels: bug
